# 開発用の構成
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 80:80
    tty: true
    env_file: .env.dev
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.28
    platform: linux/x86_64
    ports:
      - 4000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=music
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=docker
      - PMA_PASSWORD=password
    ports:
      - 4040:80
    depends_on:
      mysql:
        condition: service_healthy
